# Generated by Django 5.2.5 on 2026-01-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ledger_event_id',
            field=models.CharField(blank=True, help_text='Immutable ledger event ID for balance changes', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ledger_hash',
            field=models.CharField(blank=True, help_text='Cryptographic hash from ledger', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
