# Generated by Django 5.2.5 on 2026-01-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_ledger_event_id_account_ledger_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
