# Generated by Django 5.2.5 on 2026-01-21 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='positive_amount',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='tasks_audit_model_n_df9cb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='tasks_audit_user_id_330bc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='tasks_audit_action_aff150_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tasks_trans_transac_2a7c44_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tasks_trans_from_ac_e9dc56_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tasks_trans_to_acco_72ecc5_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tasks_trans_status_0240e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='tasks_trans_transac_97a414_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='converted_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ledger_event_id',
            field=models.CharField(blank=True, help_text='Immutable ledger event ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ledger_hash',
            field=models.CharField(blank=True, help_text='Cryptographic hash from ledger', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
    ]
